name: Deploy Infra

on:
  push:
    branches: 
      - main
  workflow_dispatch:
  
env:
  location: eastus
  resourceGroupName: logicapp-secure-apim-rg    

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Azure Login
        uses: Azure/login@v1.1
        with:          
          creds: ${{ secrets.SP_AZURE_CREDENTIALS }}          
          enable-AzPSSession: false
        
      - name: Bicep Build
        uses: aliencube/bicep-build-actions@v0.1
        with:
          files: bicep/main.bicep          
          
      - name: Create Resource Group
        run: |
         az group create -n ${{ env.resourceGroupName }} -l ${{ env.location }}            

      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.0
        with:        
          tokenPrefix: __        
          tokenSuffix: __        
          files: '["bicep/main.parameters.json"]'
        env:
          location: ${{ env.location }}
          audience: ${{ secrets.AUDIENCE }}
          tenantId: ${{ secrets.TENANT_ID }}
          publisherName: ${{ secrets.PUBLISHER_NAME }}
          publisherEmail: ${{ secrets.PUBLISHER_EMAIL }}

      - name: Deploy Infra
        id: deployapim
        uses: Azure/arm-deploy@v1.0.1
        with:        
          scope: resourcegroup          
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}          
          region: ${{ env.LOCATION }}        
          resourceGroupName: ${{ env.resourceGroupName }}        
          template: bicep/main.json   
          parameters: bicep/main.parameters.json
          deploymentMode: Incremental     
